apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: learn-otel
resources:
  - ../../base/postgres
  - ../../base/redis
  - ../../base/nats
  - ../../base/frontend-gateway
  - ../../base/catalog-service
  - ../../base/order-service
  - ../../base/pricing-service
  - ../../base/kitchen-service
  - ../../base/delivery-service
  - ../../base/notification-service
  - ../../base/load-generator
