apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: learn-otel
resources:
  - ../../base/postgres
  - ../../base/redis
  - ../../base/nats
  - ../../base/frontend-gateway
  - ../../base/catalog-service
  - ../../base/order-service
  - ../../base/pricing-service
  - ../../base/kitchen-service
  - ../../base/delivery-service
  - ../../base/notification-service
  - ../../base/load-generator
  - ../../base/image-updater
images:
  - name: ghcr.io/skarj/frontend-gateway
    newTag: latest
  - name: ghcr.io/skarj/catalog-service
    newTag: latest
  - name: ghcr.io/skarj/order-service
    newTag: latest
  - name: ghcr.io/skarj/pricing-service
    newTag: latest
  - name: ghcr.io/skarj/kitchen-service
    newTag: latest
  - name: ghcr.io/skarj/delivery-service
    newTag: latest
  - name: ghcr.io/skarj/notification-service
    newTag: latest
  - name: ghcr.io/skarj/load-generator
    newTag: latest
