apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  labels:
    app: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
        - name: load-generator
          image: ghcr.io/skarj/load-generator:latest
          env:
            - name: TARGET_URL
              value: http://frontend-gateway:8000
            - name: MIN_INTERVAL
              value: "2.0"
            - name: MAX_INTERVAL
              value: "3.5"
            - name: BURST_PROBABILITY
              value: "0.02"
            - name: OTLP_ENDPOINT
              value: "http://signoz-otel-collector.observability.svc.cluster.local:4317"
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
