apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statefulset.yaml
  - service.yaml
configMapGenerator:
  - name: postgres-init-scripts
    files:
      - init-multiple-dbs.sh
secretGenerator:
  - name: postgres-credentials
    literals:
      - username=app
      - password=learnotel-dev-pw
