name: Build and Push

on:
  push:
    branches: [main]
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Filter changes
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          filters: |
            frontend-gateway:
              - 'libs/common/**'
              - 'services/frontend-gateway/**'
            catalog-service:
              - 'libs/common/**'
              - 'services/catalog-service/**'
            order-service:
              - 'libs/common/**'
              - 'services/order-service/**'
            pricing-service:
              - 'libs/common/**'
              - 'services/pricing-service/**'
            kitchen-service:
              - 'libs/common/**'
              - 'services/kitchen-service/**'
            delivery-service:
              - 'libs/common/**'
              - 'services/delivery-service/**'
            notification-service:
              - 'libs/common/**'
              - 'services/notification-service/**'
            load-generator:
              - 'libs/common/**'
              - 'services/load-generator/**'

  build:
    needs: detect-changes

    if: ${{ needs.detect-changes.outputs.services != '[]' }}

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # Required to build for ARM64 on x86 GitHub runners
      - name: Set up QEMU
        uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4.3.0

      # Enables advanced Docker features, like building for multiple architectures and better caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.service }}
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: services/${{ matrix.service }}/Dockerfile
          platforms: linux/arm64 # build for ARM64 architecture
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Optimized caching
          cache-from: type=gha
          cache-to: type=gha,mode=max
